CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    password_hash     VARCHAR(255) NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    stripe_customer_id VARCHAR(255),
    created_at        TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_users_email ON users (email);
