CREATE TABLE listings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id       BIGINT        NOT NULL REFERENCES users (id),
    title           VARCHAR(140)  NOT NULL,
    category        VARCHAR(30)   NOT NULL,
    description     VARCHAR(4000) NOT NULL,
    item_condition  VARCHAR(20)   NOT NULL,
    start_price     NUMERIC(12, 2) NOT NULL,
    bid_increment   NUMERIC(12, 2) NOT NULL,
    current_price   NUMERIC(12, 2) NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    start_at        TIMESTAMP,
    end_at          TIMESTAMP,
    pickup_location VARCHAR(255),
    created_at      TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP     NOT NULL DEFAULT now()
);

CREATE TABLE listing_photos (
    listing_id BIGINT        NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    url        VARCHAR(1000) NOT NULL,
    position   INTEGER       NOT NULL,
    PRIMARY KEY (listing_id, position)
);

CREATE INDEX ix_listings_seller_id ON listings (seller_id);
CREATE INDEX ix_listings_status ON listings (status);
CREATE INDEX ix_listings_category ON listings (category);
CREATE INDEX ix_listings_end_at ON listings (end_at);
