-- P2: real-time bidding. Adds the bids history table plus the denormalized
-- highest-bidder / bid-count / optimistic-version columns on listings.

ALTER TABLE listings ADD COLUMN version           BIGINT  NOT NULL DEFAULT 0;
ALTER TABLE listings ADD COLUMN current_bidder_id BIGINT  REFERENCES users (id);
ALTER TABLE listings ADD COLUMN bid_count         INTEGER NOT NULL DEFAULT 0;

CREATE TABLE bids (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT         NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    bidder_id  BIGINT         NOT NULL REFERENCES users (id),
    amount     NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX ix_bids_listing_id ON bids (listing_id);
-- Serves "highest / most recent bids first" history reads.
CREATE INDEX ix_bids_listing_amount ON bids (listing_id, amount DESC);
CREATE INDEX ix_listings_current_bidder_id ON listings (current_bidder_id);
