-- P3: payment spine. Deposit holds gate bidding; settlement captures the winner and
-- releases losers on close; processed webhook events are deduped for idempotency.

CREATE TABLE payment_holds (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT         NOT NULL REFERENCES users (id),
    listing_id               BIGINT         NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    stripe_payment_intent_id VARCHAR(255)   NOT NULL,
    amount                   NUMERIC(12, 2) NOT NULL,
    status                   VARCHAR(20)    NOT NULL,
    idempotency_key          VARCHAR(120)   NOT NULL,
    created_at               TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at               TIMESTAMP      NOT NULL DEFAULT now(),
    -- One hold per buyer per auction; the unique key also backs idempotent retries.
    CONSTRAINT uq_payment_holds_user_listing UNIQUE (user_id, listing_id),
    CONSTRAINT uq_payment_holds_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX ix_payment_holds_listing_id ON payment_holds (listing_id);

CREATE TABLE settlements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- One settlement per listing — the idempotency guard for close-on-settle.
    listing_id     BIGINT         NOT NULL UNIQUE REFERENCES listings (id) ON DELETE CASCADE,
    winning_bid_id BIGINT         REFERENCES bids (id),
    final_amount   NUMERIC(12, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    created_at     TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE TABLE processed_webhook_events (
    event_id    VARCHAR(255) PRIMARY KEY,
    type        VARCHAR(120) NOT NULL,
    received_at TIMESTAMP    NOT NULL DEFAULT now()
);
