package com.bidwise.payment;

import com.bidwise.listing.Listing;
import com.bidwise.user.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.time.Instant;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * A buyer's deposit pre-authorization for one auction: a manual-capture hold created
 * before they may bid. Exactly one hold exists per (user, listing) — enforced by a
 * unique constraint and a stable idempotency key — so retries never double-hold.
 *
 * <p>State changes go through {@link #capture()} / {@link #voidHold()} rather than
 * setters. Getters are generated by Lombok.
 */
@Entity
@Table(
        name = "payment_holds",
        uniqueConstraints = @UniqueConstraint(
                name = "uq_payment_holds_user_listing",
                columnNames = {"user_id", "listing_id"}))
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED) // required by JPA
public class PaymentHold {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "listing_id", nullable = false)
    private Listing listing;

    @Column(name = "stripe_payment_intent_id", nullable = false, length = 255)
    private String stripePaymentIntentId;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentHoldStatus status;

    @Column(name = "idempotency_key", nullable = false, unique = true, length = 120)
    private String idempotencyKey;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Creates an {@code AUTHORIZED} hold for the given buyer and auction. */
    public PaymentHold(
            User user,
            Listing listing,
            String stripePaymentIntentId,
            BigDecimal amount,
            String idempotencyKey) {
        this.user = user;
        this.listing = listing;
        this.stripePaymentIntentId = stripePaymentIntentId;
        this.amount = amount;
        this.idempotencyKey = idempotencyKey;
        this.status = PaymentHoldStatus.AUTHORIZED;
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /** Marks this hold captured (the buyer was charged). */
    public void capture() {
        this.status = PaymentHoldStatus.CAPTURED;
        this.updatedAt = Instant.now();
    }

    /** Marks this hold voided (the deposit was released). */
    public void voidHold() {
        this.status = PaymentHoldStatus.VOIDED;
        this.updatedAt = Instant.now();
    }
}
