package com.bidwise.payment;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Dedup record for inbound webhook events. The provider's event id is the primary key,
 * so a redelivered event collides on insert and is skipped — this is what makes webhook
 * fulfillment idempotent (the same event delivered twice has effect once).
 *
 * <p>Getters are generated by Lombok.
 */
@Entity
@Table(name = "processed_webhook_events")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED) // required by JPA
public class ProcessedWebhookEvent {

    @Id
    @Column(name = "event_id", nullable = false, length = 255)
    private String eventId;

    @Column(nullable = false, length = 120)
    private String type;

    @Column(name = "received_at", nullable = false, updatable = false)
    private Instant receivedAt;

    public ProcessedWebhookEvent(String eventId, String type) {
        this.eventId = eventId;
        this.type = type;
        this.receivedAt = Instant.now();
    }
}
