package com.bidwise.listing;

import com.bidwise.user.User;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OrderColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * An auction listing created by a seller. Mirrors the {@code listings} table.
 *
 * <p>State changes go through guarded domain methods ({@link #publish()},
 * {@link #cancel()}, {@link #applyEdits}) rather than setters, so invariants live
 * in one place. Getters are generated by Lombok.
 */
@Entity
@Table(name = "listings")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED) // required by JPA
public class Listing {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "seller_id", nullable = false)
    private User seller;

    @Column(nullable = false, length = 140)
    private String title;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private Category category;

    @Column(nullable = false, length = 4000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "item_condition", nullable = false, length = 20)
    private ItemCondition condition;

    @ElementCollection
    @CollectionTable(name = "listing_photos", joinColumns = @JoinColumn(name = "listing_id"))
    @OrderColumn(name = "position")
    @Column(name = "url", nullable = false, length = 1000)
    private List<String> photos = new ArrayList<>();

    @Column(name = "start_price", nullable = false, precision = 12, scale = 2)
    private BigDecimal startPrice;

    @Column(name = "bid_increment", nullable = false, precision = 12, scale = 2)
    private BigDecimal bidIncrement;

    @Column(name = "current_price", nullable = false, precision = 12, scale = 2)
    private BigDecimal currentPrice;

    /** Highest bidder so far (and the winner once the auction has ended). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "current_bidder_id")
    private User currentBidder;

    @Column(name = "bid_count", nullable = false)
    private int bidCount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ListingStatus status;

    /**
     * Seller-chosen auction length. The end time is derived from it on
     * {@link #publish()}; clients never supply {@code endAt} directly.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AuctionDuration duration;

    @Column(name = "start_at")
    private Instant startAt;

    @Column(name = "end_at")
    private Instant endAt;

    @Column(name = "pickup_location", length = 255)
    private String pickupLocation;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Optimistic-lock version. The hot bid path updates price atomically via a
     * guarded SQL statement, so this mainly guards slower edit/close transactions.
     */
    @Version
    private Long version;

    /**
     * Creates a new listing in {@link ListingStatus#DRAFT}. The current price starts
     * at the start price; the auction window opens only on {@link #publish()}.
     */
    public Listing(
            User seller,
            String title,
            Category category,
            String description,
            ItemCondition condition,
            List<String> photos,
            BigDecimal startPrice,
            BigDecimal bidIncrement,
            String pickupLocation,
            AuctionDuration duration) {
        this.seller = seller;
        this.title = title;
        this.category = category;
        this.description = description;
        this.condition = condition;
        this.photos = photos == null ? new ArrayList<>() : new ArrayList<>(photos);
        this.startPrice = startPrice;
        this.bidIncrement = bidIncrement;
        this.currentPrice = startPrice;
        this.pickupLocation = pickupLocation;
        this.duration = duration;
        this.status = ListingStatus.DRAFT;
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /** True if the given user id is the owner of this listing. */
    public boolean isOwnedBy(Long userId) {
        return seller != null && seller.getId() != null && seller.getId().equals(userId);
    }

    /**
     * Edits the mutable presentation/pricing fields. Allowed only while the listing
     * is still {@code DRAFT} or {@code ACTIVE}.
     */
    public void applyEdits(
            String title,
            Category category,
            String description,
            ItemCondition condition,
            List<String> photos,
            BigDecimal startPrice,
            BigDecimal bidIncrement,
            String pickupLocation,
            AuctionDuration duration) {
        if (status != ListingStatus.DRAFT && status != ListingStatus.ACTIVE) {
            throw new IllegalListingStateException(
                    "Listing can only be edited while it is a draft or active");
        }
        this.title = title;
        this.category = category;
        this.description = description;
        this.condition = condition;
        this.photos = photos == null ? new ArrayList<>() : new ArrayList<>(photos);
        this.startPrice = startPrice;
        this.bidIncrement = bidIncrement;
        // No bids exist in P1, so the current price tracks the start price.
        if (status == ListingStatus.DRAFT) {
            this.currentPrice = startPrice;
        }
        this.pickupLocation = pickupLocation;
        this.duration = duration;
        this.updatedAt = Instant.now();
    }

    /**
     * Publishes a draft: opens the auction window now and makes it searchable. The
     * end time is computed server-side from the seller's chosen {@link #duration}
     * ({@code endAt = now + duration}); it is never supplied by the client.
     */
    public void publish() {
        if (status != ListingStatus.DRAFT) {
            throw new IllegalListingStateException("Only a draft listing can be published");
        }
        if (duration == null) {
            throw new IllegalListingStateException("Listing must have an auction duration");
        }
        Instant now = Instant.now();
        this.startAt = now;
        this.endAt = now.plus(duration.toDuration());
        this.status = ListingStatus.ACTIVE;
        this.updatedAt = now;
    }

    /**
     * Marks an ended auction as sold once its winning deposit has been captured
     * (settlement, P3). Idempotent guard: only an {@code ENDED} listing can be sold.
     */
    public void markSold() {
        if (status != ListingStatus.ENDED) {
            throw new IllegalListingStateException("Only an ended auction can be marked sold");
        }
        this.status = ListingStatus.SOLD;
        this.updatedAt = Instant.now();
    }

    /** Cancels an active listing (no winner). */
    public void cancel() {
        if (status != ListingStatus.ACTIVE) {
            throw new IllegalListingStateException("Only an active listing can be cancelled");
        }
        this.status = ListingStatus.CLOSED;
        this.updatedAt = Instant.now();
    }

    /**
     * Ends an active auction whose time is up: {@code ENDED} when there is a winning
     * bidder (awaiting settlement in P3), otherwise {@code CLOSED} (no bids). The
     * winner is the current highest bidder. Idempotent guard: only an {@code ACTIVE}
     * listing can be ended.
     */
    public void endAuction() {
        if (status != ListingStatus.ACTIVE) {
            throw new IllegalListingStateException("Only an active listing can be ended");
        }
        this.status = currentBidder != null ? ListingStatus.ENDED : ListingStatus.CLOSED;
        this.updatedAt = Instant.now();
    }
}
